1a

In [ ]:
import torch

# Tensor creation
a = torch.tensor([1, 2, 3])
b = torch.zeros((2, 3))
c = torch.ones((3, 3))
d = torch.rand((2, 2))
e = torch.arange(0, 10, 2)

print(a.dtype)
print(b.shape)

torch.int64
torch.Size([2, 3])


1b

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print(x + y)
print(x * y)


tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [ ]:
m = torch.tensor([[1, 2, 3]])
n = torch.tensor([10, 20, 30])

print(m + n)

tensor([[11, 22, 33]])


In [ ]:
t = torch.tensor([[1, 2], [3, 4]])
print(t[0, 1])

tensor(2)


In [ ]:
r = torch.arange(6)
print(r.reshape(2, 3))

tensor([[0, 1, 2],
        [3, 4, 5]])


1c

In [ ]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2 + 2 * x + 1
y.backward()

print(x.grad)

tensor(8.)


2

In [ ]:
import tensorflow as tf

A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])

# Matrix addition
print(A + B)

# Matrix multiplication
print(tf.matmul(A, B))

# Transpose
print(tf.transpose(A))

# Determinant
print(tf.linalg.det(A))

# Inverse
print(tf.linalg.inv(A))


tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


3

In [ ]:
def perceptron(x1, x2, w1, w2, bias):
    net = x1*w1 + x2*w2 + bias
    return 1 if net >= 0 else 0

# AND Gate
print("AND Gate")
for x1 in [0,1]:
    for x2 in [0,1]:
        print(x1, x2, perceptron(x1, x2, 1, 1, -1.5))

# OR Gate
print("\nOR Gate")
for x1 in [0,1]:
    for x2 in [0,1]:
        print(x1, x2, perceptron(x1, x2, 1, 1, -0.5))


AND Gate
0 0 0
0 1 0
1 0 0
1 1 1

OR Gate
0 0 0
0 1 1
1 0 1
1 1 1


4

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# XOR data
X = torch.tensor([[0.,0.], [0.,1.], [1.,0.], [1.,1.]])
Y = torch.tensor([[0.], [1.], [1.], [0.]])

class XORNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 4)
        self.fc2 = nn.Linear(4, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        return torch.sigmoid(self.fc2(x))

model = XORNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

for epoch in range(2000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, Y)
    loss.backward()
    optimizer.step()

print(model(X).round())


tensor([[0.],
        [1.],
        [1.],
        [0.]], grad_fn=<RoundBackward0>)


5

In [ ]:
import torch
import torch.nn as nn

# Data
x = torch.linspace(0, 10, 100).reshape(-1, 1)
y = 2 * x + 3

# Model
model = nn.Linear(1, 1)
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = model(x)
    loss = criterion(y_pred, y)
    loss.backward()
    optimizer.step()

print("Weight:", model.weight.item())
print("Bias:", model.bias.item())


Weight: 2.0029995441436768
Bias: 2.980051040649414
